### ISSUE TITLE
Efficient Styling

### ISSUE THREAD

**Issue by josephgupkim** [Gov90/prj-rev-bwfs-dasmoto#2]
Just some possible improvements that could help keep your code more in line with convention and industry standards:

- Unnecessary to nest a "h4" tag inside a "p" tag. You should just keep them separate.
- If you want to style only a certain portion of a text, try using a "span" tag. "a" tags should be only used for links.
- Keep all class names, ID names, and file names lowercase.

**Comment by Gov90** [comment]
Thank you.
