### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [Gov90/prj-rev-bwfs-dasmoto#4]
A great looking project with potential for perfection by adjusting some tag choices and staying consistent with indentations.

Great job on the replication and applying everything you've learned so far! Keep it up!

Grade: Meets expectation.

**Comment by Gov90** [comment]
Thank you for your feedback.  I found it to be helpful and constructive.  This is all very new to me, so I'm glad my plodding along is working out ok.
